name: tad_pathways
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::python=3.5.2
- conda-forge::pandas=0.23.3
- conda-forge::numexpr=2.6.8
- conda-forge::numpy=1.15.2
- conda-forge::scipy=1.1.0
- conda-forge::jupyter=1.0.0
- conda-forge::xlrd=1.1.0
- conda-forge::ipykernel=4.8.1
- conda-forge::ipywidgets=6.0.0
- conda-forge::widgetsnbextension=2.0.0
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::r-base=3.4.1
- conda-forge::r-essentials=3.4.1
- conda-forge::r-codetools=0.2-15
- conda-forge::readline=6.2
- conda-forge::r-readr=1.1.1
- conda-forge::r-gridextra=2.3
- conda-forge::r-optparse=1.6.0
- conda-forge::r-dplyr=0.7.6
- conda-forge::r-tidyr=0.8.1
- bioconda::bioconductor-biomart=2.36.1
- bioconda::gseapy=0.9.8
